name: 'PR Check'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

  lint-and-test:
    needs: checkout
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: |
          echo "Test"
          # npm run lint
      - name: Install
        run: |
          echo "Test"
          # npm run test
  build-frontend:
    needs: lint-and-test
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Build Frontend
        run: |
          echo "Build Frontend"
          # npm run test
  build-backend:
    needs: lint-and-test
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Build Backend
        run: |
          echo "Build Backend"
          # npm run test
  deploy-staging:
    needs: [build-backend, build-frontend]
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend
        run: |
          echo "Deploy Frontend"
      - name: Build Backend
        run: |
          echo "Deploy Backend"
  deploy-production:
    needs: [deploy-staging]
    name: Deploy Production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend
        run: |
          echo "Deploy Frontend"
      - name: Build Backend
        run: |
          echo "Deploy Backend"
